title: Big Picture School
description: Using AI to teach the core principles of major disciplines to encourage interdisciplinary thought.
theme: just-the-docs
favicon_ico: "/assets/images/favicon.ico"

url: https://bigpictureschool.com
ga_tracking: G-1YB8FF6HCN




