title: Big Picture School
description: Using AI to teach the core principles of major disciplines for the purpose of encouraging interdisciplinary thought.
theme: just-the-docs

url: https://bigpictureschool.com
ga_tracking: G-1YB8FF6HCN




