title: Big Picture School
description: Teaching the core principles of major disciplines to encourage interdisciplinary thought.
theme: just-the-docs
favicon_ico: "/assets/images/favicon.ico"

url: https://bigpictureschool.com
ga_tracking: G-1YB8FF6HCN
footer_content: "<a href=\"https://bigpictureschool.com\">Big Picture School</a> © 2024 by <a href=\"https://bigpictureschool.com\">Big Picture School</a> is licensed under <a href=\"https://creativecommons.org/licenses/by-nc/4.0\">CC BY-NC 4.0</a>."
